version: '3.9'

services:
    freelas_dev:
        container_name: freelas_dev
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
            - .:/usr/share/nginx
        networks:
            - networkis

    freelas_db:
        container_name: freelas_db
        image: postgres:17
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: freelas
            POSTGRES_PASSWORD: freelas
            POSTGRES_DB: freelas
        volumes:
            - ./.docker/pgdata:/var/lib/postgresql/data
        networks:
            - networkis

networks: 
    networkis:
        driver: bridge
